Add missing include
Compiling src/gpio.c emmits a warning:
../../../src/gpio.c:213:24: warning: implicit declaration of function ‘strnlen’ [-Wimplicit-function-declaration]
  ret = write (fd, dir, strnlen (dir, 3));
                        ^~~~~~~

Add the missing include <string.h>.
While at it put <unistd.h> import to a proper place.

Signed-off-by: Benedikt Spranger <b.spranger@linutronix.de>